In [1]:
import numpy as np
import pandas as pd

In [2]:
#小数点3桁まで表示するがIPythonのバージョン差異で動かないorz
%precision 3

pd.set_option('precision', 3)

In [3]:
#CSVを読み込む
df = pd.read_csv('data/ch2_scores_em.csv', index_col='生徒番号')
df.head()

英語  数学
生徒番号        
1     42  65
2     69  80
3     56  63
4     41  63
5     57  76

In [4]:
#配列に入れる
scores = np.array(df['英語'])[:10]
scores

array([42, 69, 56, 41, 57, 48, 65, 49, 65, 58], dtype=int64)

In [5]:
#データフレームにセットする
scores_df = pd.DataFrame({'点数':scores},index=pd.Index(['A','B','C','D','E','F','G','H','I','J'],name='生徒'))
scores_df

点数
生徒    
A   42
B   69
C   56
D   41
E   57
F   48
G   65
H   49
I   65
J   58

In [6]:
#平均値
sum(scores) / len(scores)

55.0

In [28]:
#平均値
np.mean(scores)

55.0

In [8]:
#平均値
df.mean()

英語    58.38
数学    78.88
dtype: float64

In [9]:
#平均値
scores_df.mean()

点数    55.0
dtype: float64

In [11]:
#昇順にソート
sorted_socres = np.sort(scores)
sorted_socres

array([41, 42, 48, 49, 56, 57, 58, 65, 65, 69], dtype=int64)

In [23]:
#中央値
n = len(sorted_socres)
if n % 2 == 0:
    m_1 = sorted_socres[n // 2 - 1]
    m = sorted_socres[n // 2]
#     median = (m_1 + m) / 2
    median = float((m_1 + m) / 2)
else:
#     median = sorted_socres[n // 2]
    median = float(sorted_socres[n // 2])
median
type(median)

float

In [24]:
#中央値
np.median(scores)

56.5

In [25]:
#中央値
scores_df.median()

点数    56.5
dtype: float64

In [26]:
#最頻値
pd.Series([1,1,1,2,2,3]).mode()

0    1
dtype: int64

In [27]:
#最頻値
pd.Series([1,2,3,4,5]).mode()

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [30]:
#偏差
mean = np.mean(scores)
deviation = scores - mean
deviation

array([-13.,  14.,   1., -14.,   2.,  -7.,  10.,  -6.,  10.,   3.])

In [31]:
#平均値
another_scores = [50,60,58,54,51,56,57,53,52,59]
another_mean = np.mean(another_scores)
another_mean

55.0

In [32]:
#偏差
another_deviation = another_scores - another_mean
another_deviation

array([-5.,  5.,  3., -1., -4.,  1.,  2., -2., -3.,  4.])

In [33]:
#偏差の平均を取る
np.mean(deviation)

0.0

In [34]:
#偏差の平均を取る
np.mean(another_deviation)

0.0

In [37]:
#データフレームに偏差をセットする
summary_df = scores_df.copy()
summary_df['偏差'] = deviation
summary_df

点数    偏差
生徒          
A   42 -13.0
B   69  14.0
C   56   1.0
D   41 -14.0
E   57   2.0
F   48  -7.0
G   65  10.0
H   49  -6.0
I   65  10.0
J   58   3.0

In [38]:
#偏差の平均
summary_df.mean()

点数    55.0
偏差     0.0
dtype: float64

In [43]:
#標本分散
sum(deviation ** 2) / len(deviation)

86.0

In [41]:
#標本分散
np.mean(deviation ** 2)

86.0

In [40]:
#標本分散
np.var(scores)

86.0

In [46]:
#標本分散
scores_df.var(ddof=0)

点数    86.0
dtype: float64

In [45]:
#不偏分散
sum(deviation ** 2) / (len(deviation) - 1)

95.55555555555556

In [42]:
#不偏分散
scores_df.var()

点数    95.556
dtype: float64

In [47]:
#不偏分散
np.var(scores,ddof=1)

95.55555555555556

In [48]:
#偏差の二乗
summary_df['偏差二乗'] = np.square(deviation)
summary_df

点数    偏差   偏差二乗
生徒                 
A   42 -13.0  169.0
B   69  14.0  196.0
C   56   1.0    1.0
D   41 -14.0  196.0
E   57   2.0    4.0
F   48  -7.0   49.0
G   65  10.0  100.0
H   49  -6.0   36.0
I   65  10.0  100.0
J   58   3.0    9.0

In [49]:
#それぞれの平均
summary_df.mean()

点数      55.0
偏差       0.0
偏差二乗    86.0
dtype: float64

In [50]:
#標準偏差
np.sqrt(np.var(scores, ddof=0))

9.273618495495704

In [52]:
#標準偏差
np.std(scores, ddof=0)

9.273618495495704

In [63]:
#最大値
np.max(scores)

69

In [64]:
#最小値
np.min(scores)

41

In [53]:
#範囲
np.max(scores) - np.min(scores)

28

In [56]:
#第1四分位点
scores_Q1 = np.percentile(scores, 25)
scores_Q1

48.25

In [58]:
#第2四分位点 中央値
scores_Q2 = np.percentile(scores, 50)
scores_Q2

56.5

In [59]:
#第3四分位点
scores_Q3 = np.percentile(scores, 75)
scores_Q3

63.25

In [61]:
#四分位範囲
scores_IQR = scores_Q3 - scores_Q1
scores_IQR

15.0

In [62]:
#指標をまとめて出力
pd.Series(scores).describe()

count    10.000
mean     55.000
std       9.775
min      41.000
25%      48.250
50%      56.500
75%      63.250
max      69.000
dtype: float64

In [69]:
#基準化変量
z = (scores - np.mean(scores)) / np.std(scores, ddof=0)
z

array([-1.402,  1.51 ,  0.108, -1.51 ,  0.216, -0.755,  1.078, -0.647,
        1.078,  0.323])

In [70]:
#基準化変量の平均 0にならないのおかしくないか
np.mean(z)

-1.6653345369377347e-17

In [71]:
#基準化変量の標準偏差 1にならないのおかしくないか
np.std(z, ddof=0)

0.9999999999999999

In [74]:
#偏差値
x = 50 + 10 * (scores - np.mean(scores)) / np.std(scores, ddof=0)
x

array([35.982, 65.097, 51.078, 34.903, 52.157, 42.452, 60.783, 43.53 ,
       60.783, 53.235])

In [75]:
#データフレームに偏差値をセット
scores_df['偏差値'] = x
scores_df

点数     偏差値
生徒            
A   42  35.982
B   69  65.097
C   56  51.078
D   41  34.903
E   57  52.157
F   48  42.452
G   65  60.783
H   49  43.530
I   65  60.783
J   58  53.235

In [77]:
#50人分の英語の配列
english_scores = np.array(df['英語'])
english_scores

array([42, 69, 56, 41, 57, 48, 65, 49, 65, 58, 70, 47, 51, 64, 62, 70, 71,
       68, 73, 37, 65, 65, 61, 52, 57, 57, 75, 61, 47, 54, 66, 54, 54, 42,
       37, 79, 56, 62, 62, 55, 63, 57, 57, 67, 55, 45, 66, 55, 64, 66],
      dtype=int64)

In [78]:
#指標をまとめて出力
pd.Series(english_scores).describe()

count    50.00
mean     58.38
std       9.80
min      37.00
25%      54.00
50%      57.50
75%      65.00
max      79.00
dtype: float64

In [79]:
#度数
freq, _ = np.histogram(english_scores, bins=10, range=(0,100))
freq

array([ 0,  0,  0,  2,  8, 16, 18,  6,  0,  0], dtype=int64)

In [81]:
#データフレームに度数をセット
freq_class = [f'{i}~{i+10}' for i in range(0, 100, 10)]
freq_dist_df = pd.DataFrame({'度数':freq},index=pd.Index(freq_class, name='階級'))
freq_dist_df

度数
階級        
0~10     0
10~20    0
20~30    0
30~40    2
40~50    8
50~60   16
60~70   18
70~80    6
80~90    0
90~100   0

In [82]:
#階級値
class_value = [(i+(i+10))//2 for i in range(0, 100, 10)]
class_value

[5, 15, 25, 35, 45, 55, 65, 75, 85, 95]

In [83]:
#相対度数
rel_freq = freq / freq.sum()
rel_freq

array([0.  , 0.  , 0.  , 0.04, 0.16, 0.32, 0.36, 0.12, 0.  , 0.  ])

In [84]:
#累積相対度数
cum_rel_freq = np.cumsum(rel_freq)
cum_rel_freq

array([0.  , 0.  , 0.  , 0.04, 0.2 , 0.52, 0.88, 1.  , 1.  , 1.  ])

In [85]:
#データフレームに階級値、相対度数、累積相対度数をセット
freq_dist_df['階級値'] = class_value
freq_dist_df['相対度数'] = rel_freq
freq_dist_df['累積相対度数'] = cum_rel_freq
freq_dist_df = freq_dist_df[['階級値','度数','相対度数','累積相対度数']]
freq_dist_df

階級値  度数  相対度数  累積相対度数
階級                           
0~10      5   0  0.00    0.00
10~20    15   0  0.00    0.00
20~30    25   0  0.00    0.00
30~40    35   2  0.04    0.04
40~50    45   8  0.16    0.20
50~60    55  16  0.32    0.52
60~70    65  18  0.36    0.88
70~80    75   6  0.12    1.00
80~90    85   0  0.00    1.00
90~100   95   0  0.00    1.00

In [87]:
#階級値の最頻値
freq_dist_df.loc[freq_dist_df['度数'].idxmax(),'階級値']

65

In [101]:
import matplotlib.pyplot as plt

#グラフがnotebook上に表示されるようにする
%matplotlib

Using matplotlib backend: Qt5Agg


In [102]:
#キャンパス
fig = plt.figure(figsize=(10, 6))
ax = fig.add_subplot(111)

In [103]:
#階級数10、最小値0、最大値100
freq, _, _ = ax.hist(english_scores, bins=10, range=(0,100))

In [104]:
#X軸にラベルを付ける 日本語文字化けしとるやないか
ax.set_xlabel('点数')
ax.set_xlabel('Points')

Text(0.5, 36.50222222222221, 'Points')

In [105]:
#Y軸にラベルを付ける
ax.set_ylabel('Counts')

Text(78.72222222222221, 0.5, 'Counts')

In [119]:
#X軸に10単位の目盛りを記載
#numpy.linspace(start, stop, element, endpoint=True)
ax.set_xticks(np.linspace(0, 100, 11))

In [120]:
#Y軸に1単位の目盛りを記載
#numpy.arange(stop)
#0 ≦ n < stop
ax.set_yticks(np.arange(0, freq.max()+1))

In [121]:
#別ポップアップですでに描画されていたのだが・・・
plt.show()

In [122]:
#階級数を25、階級幅を4にしてみる
#キャンパス
fig = plt.figure(figsize=(10, 6))
ax = fig.add_subplot(111)

In [123]:
#階級数25、最小値0、最大値100
freq, _, _ = ax.hist(english_scores, bins=25, range=(0,100))

In [124]:
#X軸、Y軸のラベル
ax.set_xlabel('Points')
ax.set_ylabel('Counts')

Text(91.97222222222221, 0.5, 'Counts')

In [125]:
#X軸, Y軸の目盛り
ax.set_xticks(np.linspace(0, 100, 26))
ax.set_yticks(np.arange(0, freq.max()+1))

In [126]:
#相対度数のヒストグラムと累積相対度数の曲線を重ねて描画する
#キャンパス
fig = plt.figure(figsize=(10, 6))
ax_hist = fig.add_subplot(111)
ax_freq = ax_hist.twinx()