In [1]:
import numpy as np
import pandas as pd

In [2]:
#小数点3桁まで表示するがIPythonのバージョン差異で動かないorz
%precision 3

pd.set_option('precision', 3)

In [3]:
#CSVを読み込む
df = pd.read_csv('data/ch2_scores_em.csv', index_col='生徒番号')
df.head()

英語  数学
生徒番号        
1     42  65
2     69  80
3     56  63
4     41  63
5     57  76

In [4]:
scores = np.array(df['英語'])[:10]
scores

array([42, 69, 56, 41, 57, 48, 65, 49, 65, 58], dtype=int64)

In [5]:
#データフレームにセットする
scores_df = pd.DataFrame({'点数':scores},index=pd.Index(['A','B','C','D','E','F','G','H','I','J'],name='生徒'))
scores_df

点数
生徒    
A   42
B   69
C   56
D   41
E   57
F   48
G   65
H   49
I   65
J   58

In [6]:
#平均値
sum(scores) / len(scores)

55.0

In [28]:
#平均値
np.mean(scores)

55.0

In [8]:
#平均値
df.mean()

英語    58.38
数学    78.88
dtype: float64

In [9]:
#平均値
scores_df.mean()

点数    55.0
dtype: float64

In [11]:
sorted_socres = np.sort(scores)
sorted_socres

array([41, 42, 48, 49, 56, 57, 58, 65, 65, 69], dtype=int64)

In [23]:
#中央値
n = len(sorted_socres)
if n % 2 == 0:
    m_1 = sorted_socres[n // 2 - 1]
    m = sorted_socres[n // 2]
#     median = (m_1 + m) / 2
    median = float((m_1 + m) / 2)
else:
#     median = sorted_socres[n // 2]
    median = float(sorted_socres[n // 2])
median
type(median)

float

In [24]:
#中央値
np.median(scores)

56.5

In [25]:
#中央値
scores_df.median()

点数    56.5
dtype: float64

In [26]:
#最頻値
pd.Series([1,1,1,2,2,3]).mode()

0    1
dtype: int64

In [27]:
#最頻値
pd.Series([1,2,3,4,5]).mode()

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [30]:
#偏差
mean = np.mean(scores)
deviation = scores - mean
deviation

array([-13.,  14.,   1., -14.,   2.,  -7.,  10.,  -6.,  10.,   3.])

In [31]:
#平均値
another_scores = [50,60,58,54,51,56,57,53,52,59]
another_mean = np.mean(another_scores)
another_mean

55.0

In [32]:
#偏差
another_deviation = another_scores - another_mean
another_deviation

array([-5.,  5.,  3., -1., -4.,  1.,  2., -2., -3.,  4.])

In [33]:
#偏差の平均を取る
np.mean(deviation)

0.0

In [34]:
np.mean(another_deviation)

0.0

In [37]:
#データフレームに偏差をセットする
summary_df = scores_df.copy()
summary_df['偏差'] = deviation
summary_df

点数    偏差
生徒          
A   42 -13.0
B   69  14.0
C   56   1.0
D   41 -14.0
E   57   2.0
F   48  -7.0
G   65  10.0
H   49  -6.0
I   65  10.0
J   58   3.0

In [38]:
#偏差の平均
summary_df.mean()

点数    55.0
偏差     0.0
dtype: float64

In [43]:
#標本分散
sum(deviation ** 2) / len(deviation)

86.0

In [41]:
#標本分散
np.mean(deviation ** 2)

86.0

In [40]:
np.var(scores)

86.0

In [46]:
scores_df.var(ddof=0)

点数    86.0
dtype: float64

In [45]:
#不変分散
sum(deviation ** 2) / (len(deviation) - 1)

95.55555555555556

In [42]:
scores_df.var()

点数    95.556
dtype: float64

In [47]:
np.var(scores,ddof=1)

95.55555555555556

In [48]:
#偏差の二乗
summary_df['偏差二乗'] = np.square(deviation)
summary_df

点数    偏差   偏差二乗
生徒                 
A   42 -13.0  169.0
B   69  14.0  196.0
C   56   1.0    1.0
D   41 -14.0  196.0
E   57   2.0    4.0
F   48  -7.0   49.0
G   65  10.0  100.0
H   49  -6.0   36.0
I   65  10.0  100.0
J   58   3.0    9.0

In [49]:
summary_df.mean()

点数      55.0
偏差       0.0
偏差二乗    86.0
dtype: float64

In [50]:
#標準偏差
np.sqrt(np.var(scores, ddof=0))

9.273618495495704

In [52]:
np.std(scores, ddof=0)

9.273618495495704